#ifndef MATHFUNCTIONS_GLOBAL_H
#define MATHFUNCTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATHFUNCTIONS_LIBRARY)
#  define MATHFUNCTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATHFUNCTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATHFUNCTIONS_GLOBAL_H
